name: Sync Raw Lambda Files from S3 to GitHub (Filtered Sync)

on:
  workflow_dispatch:
jobs: 
  sync-s3-to-github:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync raw files from S3 to repository root
        run: |
          aws s3 cp s3://lambda-pub-files/ ./ --recursive

      - name: Commit and push to GitHub
        run: |
          git config user.name "Manojkumar"
          git config user.email "g.manojkumar@p3fusion.com"

          git add .
          git diff-index --quiet HEAD || git commit -m "Sync raw Lambda files from S3"
          git pull --rebase origin main
          git push
